//revive.cpp

#include "config.cpp"
#include "define.hpp"
#include "rev_cam_dialog.hpp"
#include "respawn_button_1.hpp"
#include "respawn_button_2.hpp"
#include "respawn_button_3.hpp"
#include "respawn_button_4.hpp"
#include "respawn_button_1b.hpp"
#include "respawn_button_1c.hpp"
#include "respawn_button_2b.hpp"
#include "respawn_button_3b.hpp"
#include "respawn_button_4b.hpp"
#include "respawn_button_1map.hpp"
#include "respawn_button_2map.hpp"
#include "respawn_button_3map.hpp"
#include "respawn_button_4map.hpp"
#include "OK_map.hpp"
#include "dead_cam_dialog.hpp"